{
 "title": "Hit count",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "paths", "query": "label_values(path)" }
  ]
 },
 "panels": [
  {
   "title": "[create] events 24h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_total{kubernetes_namespace=\"prod\",app=\"saver\",path=\"/create\"}[1d]))"
    }
   ]
  },
  {
   "title": "[test] events 24h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_total{kubernetes_namespace=\"prod\",app=\"runner\",path=\"/run_cyber_dojo_sh\"}[24h]))"
    }
   ]
  },
  {
   "title": "[diff] events 24h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_total{kubernetes_namespace=\"prod\",app=\"differ\",path=\"/diff\"}[24h]))"
    }
   ]
  },
  {
   "title": "runner.run_cyber_dojo_sh(...) duration [1h] average",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "secs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{kubernetes_namespace=\"prod\",app=\"runner\",path=\"/run_cyber_dojo_sh\"}[1h])) / sum(rate(http_server_request_duration_seconds_count{kubernetes_namespace=\"prod\",app=\"runner\",path=\"/run_cyber_dojo_sh\"}[1h]))"
    }
   ]
  },
  {
   "title": "runner.run_cyber_dojo_sh(...) duration 95% quartile [1h]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "secs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_server_request_duration_seconds_bucket{kubernetes_namespace=\"prod\",app=\"runner\",path=\"/run_cyber_dojo_sh\"}[1h])) by (le))"
    }
   ]
  },
  {
   "title": "runner:/run_cyber_dojo_sh rate[10m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_total{kubernetes_namespace=\"prod\",app=\"runner\",path=\"/run_cyber_dojo_sh\"}[10m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "saver:/create rate[10m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_total{kubernetes_namespace=\"prod\",app=\"saver\",path=\"/create\"}[10m])"
    }
   ]
  },
  {
   "title": "saver: response time [5m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(http_server_request_duration_seconds_sum{kubernetes_namespace=\"prod\",app=\"saver\"}[5m]))"
    }
   ]
  },
  {
   "title": "average differ.diff duration [15m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "secs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{kubernetes_namespace=\"prod\",app=\"differ\",path=\"/diff\"}[15m])) / sum(rate(http_server_request_duration_seconds_count{kubernetes_namespace=\"prod\",app=\"differ\",path=\"/diff\"}[15m]))"
    }
   ]
  },
  {
   "title": "differ:/diff  rate[15m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{kubernetes_namespace=\"prod\",app=\"differ\",path=\"/diff\"}[15m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "custom:/names rate[15m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{app=\"custom-start-points\",path=\"/names\"}[15m]))"
    }
   ]
  },
  {
   "title": "exercises:/manifests rate[15m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{app=\"exercises-start-points\",path=\"/manifests\"}[15m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "languages:/names rate[15m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{app=\"languages-start-points\",path=\"/names\"}[15m]))"
    }
   ]
  },
  {
   "title": "avatar:/names rate[15m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_total{app=\"avatars\",path=\"/image/:id\"}[15m]))",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}