{
 "title": "Hit count",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "paths", "query": "label_values(path)" }
  ]
 },
 "panels": [
  {
   "title": "runner",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(runner_requests_total{path=\"/run_cyber_dojo_sh\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "ragger",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(ragger_requests_total{path=\"/colour\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "saver",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(saver_requests_total{path=\"/batch\"}[5m]))"
    }
   ]
  },
  {
   "title": "differ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(differ_requests_total{path=\"/diff\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "languages",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(languages_requests_total{path=\"/names\"}[5m]))"
    }
   ]
  },
  {
   "title": "exercises",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(exercises_requests_total{path=\"/names\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "custom",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(custom_requests_total{path=\"/names\"}[5m]))"
    }
   ]
  },
  {
   "title": "avatars",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(avatar_requests_total{path=\"/image\"}[5m]))",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}